"""Describe your changes here

Revision ID: 35cb7f54084e
Revises: 
Create Date: 2025-01-05 16:53:07.906276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cb7f54084e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_meal_plan_recipe', 'recipe', ['recipe_id'], ['id'])  # Constraint name added here
        batch_op.drop_column('day')
        batch_op.drop_column('recipe_title')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('recipe_title', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint('fk_meal_plan_recipe', type_='foreignkey')  # Constraint name used here
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
